# special spring boot setting

---
spring:
  profiles:
    active: local
  main:
    # 關閉 spring boot logo
    banner-mode: 'off'
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+08:00"

my:
  mail:
    server: myoms.com.tw
    sender: mail@myoms.com.tw
    locale: zh-tw
your:
  date: 2010/01/01
  lists: 1,2,3,4,5

debug_mode: true

---
spring:
  profiles: local

proxy:
  domain: 'none'
  port: 0

server:
  port: 8080

---
spring:
  profiles: dev

proxy:
  domain: dev.proxy.com
  port: 3128

server:
  port: 8080


---
spring:
  profiles: stg

proxy:
  domain: stg.proxy.com
  port: 3128

server:
  port: 8080


---
spring:
  profiles: prod

proxy:
  domain: prod.proxy.com
  port: 3128

server:
  port: 8080
