# special spring boot setting
# server setting
server:
  port: 8080


# 關閉 spring boot logo
spring:
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    hibernate:
      # 為了測試，先改為 create-drop
#      ddl-auto: none
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

my:
  mail:
    server: myoms.com.tw
    sender: mail@myoms.com.tw
    locale: zh-tw
  environment: prod

your:
  date: 2010/01/01
  lists: 1,2,3,4,5

